spring:
  application:
    name: pet-care-api-gateway
  cloud:
      gateway:
        routes:
          - id: pet-care-user-service
            uri : http://localhost:8081
            predicates:
              - Path=/api/customer/**
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    web:
      exposure:
        include:
          - "gateway"
    gateway:
      enabled: true


